export { DEFAULT_SETTINGS_CONTENT_ID, SETTINGS_CONTENT_TITLE } from './config/constants/content.constants'
export { default as SettingsContentPage } from './ui/SettingsContentPage.vue'
export { default as SettingsNavigationPage } from './ui/SettingsNavigationPage.vue'
export { SETTINGS_ACCOUNT_CHANGE_EMAIL_I18N } from './config/i18n/account-change-email.i18n'
export { SETTINGS_ACCOUNT_CHANGE_PASSWORD_I18N } from './config/i18n/account-change-password.i18n'
export { SETTINGS_ACCOUNT_PERSONAL_DATA_I18N } from './config/i18n/account-personal-data.i18n'
export { SETTINGS_PAGE_ACCOUNT_I18N } from './config/i18n/account.i18n'
export { SETTINGS_PAGE_APPEARANCE_I18N } from './config/i18n/appearance.i18n'
export { SETTINGS_PAGE_DEVICES_I18N } from './config/i18n/devices.i18n'
export { SETTINGS_PAGE_FAQ_I18N } from './config/i18n/faq.i18n'
export { SETTINGS_PAGE_GENERAL_I18N } from './config/i18n/general.i18n'
export { SETTINGS_PAGE_NOTIFICATIONS_I18N } from './config/i18n/notifications.i18n'
export { SETTINGS_PAGE_ROADMAP_I18N } from './config/i18n/roadmap.i18n'
export { SETTINGS_PAGE_STORAGE_I18N } from './config/i18n/storage.i18n'
