import {
  MB_IN_BYTES,
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP,
  MEDIA_UPLOAD_TYPE_LABEL_MAP,
  MEDIA_VALIDATION_OPTIONS_MAP,
  USER_NICKNAME_MAX_LENGTH,
  VALIDATION_PATTERNS
} from 'global-shared'

const accountAvatarValidation = MEDIA_VALIDATION_OPTIONS_MAP.avatar

export const SETTINGS_ACCOUNT_AVATAR_ALLOWED_TYPES =
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP[accountAvatarValidation.supportedKindMediaType]
export const SETTINGS_ACCOUNT_AVATAR_ALLOWED_TYPES_LABEL = SETTINGS_ACCOUNT_AVATAR_ALLOWED_TYPES.map(
  (type) => MEDIA_UPLOAD_TYPE_LABEL_MAP[type]
).join(', ')
export const SETTINGS_ACCOUNT_AVATAR_MAX_MB = accountAvatarValidation.maxMb
export const SETTINGS_ACCOUNT_AVATAR_MAX_FILE_SIZE = accountAvatarValidation.maxMb * MB_IN_BYTES
export const SETTINGS_ACCOUNT_NICKNAME_INPUT_ATTRS = {
  maxLength: USER_NICKNAME_MAX_LENGTH
}
export const SETTINGS_EMAIL_PATTERN = new RegExp(VALIDATION_PATTERNS.email)
