import {
  MB_IN_BYTES,
  MEDIA_AVATAR_VALIDATION_OPTIONS,
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP,
  MEDIA_UPLOAD_TYPE_LABEL_MAP,
  VALIDATION_PATTERNS
} from 'global-shared'

export const SETTINGS_ACCOUNT_AVATAR_ALLOWED_TYPES =
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP[MEDIA_AVATAR_VALIDATION_OPTIONS.supportedKindMediaType]
export const SETTINGS_ACCOUNT_AVATAR_ALLOWED_TYPES_LABEL = SETTINGS_ACCOUNT_AVATAR_ALLOWED_TYPES.map(
  (type) => MEDIA_UPLOAD_TYPE_LABEL_MAP[type]
).join(', ')
export const SETTINGS_ACCOUNT_AVATAR_MAX_MB = MEDIA_AVATAR_VALIDATION_OPTIONS.maxMb
export const SETTINGS_ACCOUNT_AVATAR_MAX_FILE_SIZE = MEDIA_AVATAR_VALIDATION_OPTIONS.maxMb * MB_IN_BYTES
export const SETTINGS_EMAIL_PATTERN = new RegExp(VALIDATION_PATTERNS.email)
