import {
  MB_IN_BYTES,
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP,
  MEDIA_VALIDATION_OPTIONS_MAP,
  MESSAGE_STATUS_VALUE
} from 'global-shared'

import { CHAT_ROOM_CONTENT_I18N } from './i18n'

export const ROOM_MESSAGES_PAGE_LIMIT = 30
export const ROOM_MESSAGES_PRELOAD_EDGE_ITEMS = 20
export const CHAT_ROOM_CONTENT_VIEW_QUERY_KEY = 'chat-view'
export const CHAT_ROOM_CONTENT_VIEW = {
  TEXT: 'text',
  CALL: 'call'
} as const
export const ROOM_CALL_PANEL_DISPLAY_MODE = {
  FOCUS: 'focus',
  GRID: 'grid'
} as const
export const ROOM_CALL_PANEL_DISPLAY_MODE_TOGGLE_I18N = {
  [ROOM_CALL_PANEL_DISPLAY_MODE.FOCUS]: CHAT_ROOM_CONTENT_I18N.roomCallGridDisplayMode,
  [ROOM_CALL_PANEL_DISPLAY_MODE.GRID]: CHAT_ROOM_CONTENT_I18N.roomCallFocusDisplayMode
} as const
export const ROOM_CALL_TILE_REMOTE_ACTION_TEXT = {
  HIDE: 'hide',
  MUTE: 'mute',
  SHOW: 'show',
  UNMUTE: 'unmute'
} as const
export const ROOM_CALL_QUICK_COMMAND = {
  NO: 'no',
  OK: 'ok',
  RAISE_HAND: 'raise-hand',
  YES: 'yes'
} as const
export const ROOM_CALL_QUICK_COMMANDS = [
  {
    i18n: CHAT_ROOM_CONTENT_I18N.roomCallQuickCommandRaiseHand,
    id: ROOM_CALL_QUICK_COMMAND.RAISE_HAND
  },
  {
    i18n: CHAT_ROOM_CONTENT_I18N.roomCallQuickCommandOk,
    id: ROOM_CALL_QUICK_COMMAND.OK
  },
  {
    i18n: CHAT_ROOM_CONTENT_I18N.roomCallQuickCommandYes,
    id: ROOM_CALL_QUICK_COMMAND.YES
  },
  {
    i18n: CHAT_ROOM_CONTENT_I18N.roomCallQuickCommandNo,
    id: ROOM_CALL_QUICK_COMMAND.NO
  }
] as const
export const ROOM_CALL_QUICK_COMMANDS_TOGGLE_I18N = CHAT_ROOM_CONTENT_I18N.roomCallQuickCommands
export const ROOM_CALL_QUICK_COMMAND_ICON_SIZE = '20px'
export const ROOM_CALL_TILE_SELF_CONTROL_ICON_SIZE = '20px'
export const ROOM_CALL_TILE_STATE_ICON_SIZE = '16px'
export const MESSAGE_READ_VISIBILITY_RATIO = 0.5
export const MESSAGE_RANGE_GAP_HEIGHT = 24
export const MESSAGE_VIRTUAL_ESTIMATED_HEIGHT = 96
export const MESSAGE_VIRTUAL_GAP = 4
export const MESSAGE_VIRTUAL_OVERSCAN = 8
export const MESSAGE_LOADING_PROGRESS_PERCENTAGE = 100
export const MESSAGE_BACK_TO_BOTTOM_VISIBLE_OFFSET = 120
export const MESSAGE_SCROLL_DEBUG_LOG_LABEL = '[message-scroll]'
export const MESSAGE_SCROLL_LOG_REASON = {
  DISPLAYED_LAST_MESSAGE_CHANGED: 'displayed-last-message-changed',
  INITIAL_EMPTY_LIST_FILLED: 'initial-empty-list-filled',
  INITIAL_TO_BOTTOM: 'initial-to-bottom',
  RESTORE_TO_BOTTOM: 'restore-to-bottom',
  USER_BACK_TO_BOTTOM: 'user-back-to-bottom'
} as const
export const MESSAGE_REACTION_VISIBLE_GROUP_LIMIT = 3
export const MESSAGE_REACTION_VISIBLE_USER_LIMIT = 3
export const MESSAGE_CONTEXT_MENU_WIDTH = 274
export const MESSAGE_CONTEXT_MENU_TRIGGER = {
  CONTEXT_MENU: 'contextmenu',
  LONG_PRESS: 'longpress'
} as const
export const MESSAGE_ATTACHMENT_DRAFT_KIND = {
  IMAGE: 'image',
  DOCUMENT: 'document',
  AUDIO: 'audio',
  VIDEO: 'video'
} as const
export const MESSAGE_MEDIA_GALLERY_ITEM_KIND = {
  IMAGE: 'image',
  VIDEO: 'video'
} as const
export const MESSAGE_ATTACHMENT_DRAFT_IMAGE_SIZE_PX = 56
export const MESSAGE_ATTACHMENT_FILE_CARD_HEIGHT_PX = 60
export const MESSAGE_ATTACHMENT_SCROLL_X_BAR_WIDTH_PX = 6
export const MESSAGE_ATTACHMENT_SCROLL_X_GAP_PX = 6
export const MESSAGE_ATTACHMENT_DRAFT_LIST_HEIGHT_PX =
  MESSAGE_ATTACHMENT_FILE_CARD_HEIGHT_PX + MESSAGE_ATTACHMENT_SCROLL_X_BAR_WIDTH_PX + MESSAGE_ATTACHMENT_SCROLL_X_GAP_PX
export const MESSAGE_ATTACHMENT_FILE_WIDTH_PX = MESSAGE_ATTACHMENT_DRAFT_IMAGE_SIZE_PX * 4
export const MESSAGE_ATTACHMENT_VISUAL_FILE_CARD_WIDTH_PX = 168
export const MESSAGE_AUDIO_ALLOWED_TYPES =
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP[MEDIA_VALIDATION_OPTIONS_MAP.audio.supportedKindMediaType]
export const MESSAGE_VIDEO_ALLOWED_TYPES =
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP[MEDIA_VALIDATION_OPTIONS_MAP.video.supportedKindMediaType]
export const MESSAGE_DOCUMENT_ALLOWED_TYPES =
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP[MEDIA_VALIDATION_OPTIONS_MAP.doc.supportedKindMediaType]
export const MESSAGE_ARCHIVE_ALLOWED_TYPES = MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP.archive
export const MESSAGE_IMAGE_ALLOWED_TYPES =
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP[MEDIA_VALIDATION_OPTIONS_MAP.image.supportedKindMediaType]
export const MESSAGE_ATTACHMENT_ALLOWED_TYPES = [
  ...MESSAGE_IMAGE_ALLOWED_TYPES,
  ...MESSAGE_DOCUMENT_ALLOWED_TYPES,
  ...MESSAGE_ARCHIVE_ALLOWED_TYPES,
  ...MESSAGE_AUDIO_ALLOWED_TYPES,
  ...MESSAGE_VIDEO_ALLOWED_TYPES
]
export const MESSAGE_AUDIO_MAX_MB = MEDIA_VALIDATION_OPTIONS_MAP.audio.maxMb
export const MESSAGE_AUDIO_MAX_FILE_SIZE = MESSAGE_AUDIO_MAX_MB * MB_IN_BYTES
export const MESSAGE_VIDEO_MAX_MB = MEDIA_VALIDATION_OPTIONS_MAP.video.maxMb
export const MESSAGE_VIDEO_MAX_FILE_SIZE = MESSAGE_VIDEO_MAX_MB * MB_IN_BYTES
export const MESSAGE_DOCUMENT_MAX_MB = MEDIA_VALIDATION_OPTIONS_MAP.doc.maxMb
export const MESSAGE_DOCUMENT_MAX_FILE_SIZE = MESSAGE_DOCUMENT_MAX_MB * MB_IN_BYTES
export const MESSAGE_IMAGE_MAX_MB = MEDIA_VALIDATION_OPTIONS_MAP.image.maxMb
export const MESSAGE_IMAGE_MAX_FILE_SIZE = MESSAGE_IMAGE_MAX_MB * MB_IN_BYTES
export const MESSAGE_CONTEXT_MENU_ACTION = {
  COPY_TEXT: 'copy-text',
  EDIT_MESSAGE: 'edit-message',
  REPLY_MESSAGE: 'reply-message',
  FORWARD_MESSAGE: 'forward-message',
  REACTION_PICKER: 'reaction-picker',
  PIN_MESSAGE: 'pin-message',
  UNPIN_MESSAGE: 'unpin-message',
  DELETE_MESSAGE: 'delete-message'
} as const
export const MESSAGE_DRAFT_REFERENCE_KIND = {
  REPLY: 'reply',
  FORWARD: 'forward'
} as const
export const MESSAGE_STATUS_DOT_TONE = {
  TEXT: 'text',
  ACCENT: 'accent',
  ERROR: 'error'
} as const
export const MESSAGE_TEXT_SEGMENT_KIND = {
  TEXT: 'text',
  LINK: 'link'
} as const
export const MESSAGE_STATUS_DOT_COUNT_BY_STATUS = {
  [MESSAGE_STATUS_VALUE.SENDING]: 1,
  [MESSAGE_STATUS_VALUE.UNDELIVERED]: 1,
  [MESSAGE_STATUS_VALUE.DELIVERED]: 1,
  [MESSAGE_STATUS_VALUE.READ]: 2,
  [MESSAGE_STATUS_VALUE.NONE]: 0
} as const
export const MESSAGE_STATUS_DOT_TONE_BY_STATUS = {
  [MESSAGE_STATUS_VALUE.SENDING]: MESSAGE_STATUS_DOT_TONE.TEXT,
  [MESSAGE_STATUS_VALUE.UNDELIVERED]: MESSAGE_STATUS_DOT_TONE.ERROR,
  [MESSAGE_STATUS_VALUE.DELIVERED]: MESSAGE_STATUS_DOT_TONE.TEXT,
  [MESSAGE_STATUS_VALUE.READ]: MESSAGE_STATUS_DOT_TONE.ACCENT,
  [MESSAGE_STATUS_VALUE.NONE]: MESSAGE_STATUS_DOT_TONE.TEXT
} as const
