import {
  MB_IN_BYTES,
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP,
  MEDIA_VALIDATION_OPTIONS_MAP,
  MESSAGE_STATUS_VALUE
} from 'global-shared'

export const ROOM_MESSAGES_PAGE_LIMIT = 30
export const ROOM_MESSAGES_PRELOAD_EDGE_ITEMS = 20
export const MESSAGE_READ_VISIBILITY_RATIO = 0.5
export const MESSAGE_RANGE_GAP_HEIGHT = 24
export const MESSAGE_VIRTUAL_ESTIMATED_HEIGHT = 96
export const MESSAGE_VIRTUAL_GAP = 4
export const MESSAGE_VIRTUAL_OVERSCAN = 8
export const MESSAGE_BACK_TO_BOTTOM_VISIBLE_OFFSET = 120
export const MESSAGE_REACTION_VISIBLE_GROUP_LIMIT = 3
export const MESSAGE_REACTION_VISIBLE_USER_LIMIT = 3
export const MESSAGE_CONTEXT_MENU_WIDTH = 274
export const MESSAGE_CONTEXT_MENU_TRIGGER = {
  CONTEXT_MENU: 'contextmenu',
  LONG_PRESS: 'longpress'
} as const
export const MESSAGE_ATTACHMENT_DRAFT_KIND = {
  IMAGE: 'image',
  DOCUMENT: 'document'
} as const
export const MESSAGE_ATTACHMENT_DRAFT_IMAGE_SIZE_PX = 56
export const MESSAGE_ATTACHMENT_DOCUMENT_WIDTH_PX = MESSAGE_ATTACHMENT_DRAFT_IMAGE_SIZE_PX * 3
export const MESSAGE_DOCUMENT_ALLOWED_TYPES =
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP[MEDIA_VALIDATION_OPTIONS_MAP.doc.supportedKindMediaType]
export const MESSAGE_IMAGE_ALLOWED_TYPES =
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP[MEDIA_VALIDATION_OPTIONS_MAP.image.supportedKindMediaType]
export const MESSAGE_ATTACHMENT_ALLOWED_TYPES = [...MESSAGE_IMAGE_ALLOWED_TYPES, ...MESSAGE_DOCUMENT_ALLOWED_TYPES]
export const MESSAGE_DOCUMENT_MAX_MB = MEDIA_VALIDATION_OPTIONS_MAP.doc.maxMb
export const MESSAGE_DOCUMENT_MAX_FILE_SIZE = MESSAGE_DOCUMENT_MAX_MB * MB_IN_BYTES
export const MESSAGE_IMAGE_MAX_MB = MEDIA_VALIDATION_OPTIONS_MAP.image.maxMb
export const MESSAGE_IMAGE_MAX_FILE_SIZE = MESSAGE_IMAGE_MAX_MB * MB_IN_BYTES
export const MESSAGE_CONTEXT_MENU_ACTION = {
  COPY_TEXT: 'copy-text',
  EDIT_MESSAGE: 'edit-message',
  REPLY_MESSAGE: 'reply-message',
  FORWARD_MESSAGE: 'forward-message',
  REACTION_PICKER: 'reaction-picker',
  PIN_MESSAGE: 'pin-message',
  UNPIN_MESSAGE: 'unpin-message',
  DELETE_MESSAGE: 'delete-message'
} as const
export const MESSAGE_DRAFT_REFERENCE_KIND = {
  REPLY: 'reply',
  FORWARD: 'forward'
} as const
export const MESSAGE_STATUS_DOT_TONE = {
  TEXT: 'text',
  ACCENT: 'accent',
  ERROR: 'error'
} as const
export const MESSAGE_TEXT_SEGMENT_KIND = {
  TEXT: 'text',
  LINK: 'link'
} as const
export const MESSAGE_STATUS_DOT_COUNT_BY_STATUS = {
  [MESSAGE_STATUS_VALUE.SENDING]: 1,
  [MESSAGE_STATUS_VALUE.UNDELIVERED]: 1,
  [MESSAGE_STATUS_VALUE.DELIVERED]: 1,
  [MESSAGE_STATUS_VALUE.READ]: 2,
  [MESSAGE_STATUS_VALUE.NONE]: 0
} as const
export const MESSAGE_STATUS_DOT_TONE_BY_STATUS = {
  [MESSAGE_STATUS_VALUE.SENDING]: MESSAGE_STATUS_DOT_TONE.TEXT,
  [MESSAGE_STATUS_VALUE.UNDELIVERED]: MESSAGE_STATUS_DOT_TONE.ERROR,
  [MESSAGE_STATUS_VALUE.DELIVERED]: MESSAGE_STATUS_DOT_TONE.TEXT,
  [MESSAGE_STATUS_VALUE.READ]: MESSAGE_STATUS_DOT_TONE.ACCENT,
  [MESSAGE_STATUS_VALUE.NONE]: MESSAGE_STATUS_DOT_TONE.TEXT
} as const
