export const MESSAGE_MEDIA_GALLERY_SINGLE_ITEM_TARGET_HEIGHT_PX = 260
export const MESSAGE_MEDIA_GALLERY_VIDEO_FALLBACK_ASPECT_RATIO = 16 / 9
export const MESSAGE_MEDIA_GALLERY_ITEM_MIN_ASPECT_RATIO = 0.65
export const MESSAGE_MEDIA_GALLERY_ITEM_MAX_ASPECT_RATIO = 2.2
