import { SECOND_IN_MS } from 'global-shared'

export const SOCKET_RECONNECTION_DELAY_MS = 1 * SECOND_IN_MS
export const SOCKET_MAX_RECONNECTION_DELAY_MS = 1 * SECOND_IN_MS
export const SOCKET_ACTION_ACK_TIMEOUT_MS = 15 * SECOND_IN_MS
