# .gitlab-ci.yml

stages:
  - build
  - publish

variables:
  SERVER_IMAGE: ketjo/k-room_server
  CLIENT_IMAGE: ketjo/k-room_client

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose build
  only:
    - main

publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker tag ${SERVER_IMAGE}:latest ${SERVER_IMAGE}:${CI_COMMIT_SHA}
    - docker tag ${CLIENT_IMAGE}:latest ${CLIENT_IMAGE}:${CI_COMMIT_SHA}
    - docker push ${SERVER_IMAGE}:${CI_COMMIT_SHA}
    - docker push ${CLIENT_IMAGE}:${CI_COMMIT_SHA}
  only:
    - main
