version: '3'

services:
  # db:
  #   container_name: k-room-db
  #   restart: always
  #   build: ./db/
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  # server:
  #   container_name: 'k-room-server'
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: ./server/Dockerfile
  #   ports:
  #     - '${SERVER_PORT}:${SERVER_PORT}'
  #   links:
  #     - 'db'
  # client:
  #   container_name: 'k-room-client'
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: ./client/Dockerfile
  #   ports:
  #     - '${CLIENT_PORT}:${CLIENT_PORT}'
  # docker-compose up -d zharkeev.post@gmail.com k-room.space certbot
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  client:
    container_name: 'k-room-client'
    restart: always
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - '80:80'
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw