version: '3'

services:
  server:
    image: ketjo/k-room_server:latest
    restart: always
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
  client:
    image: ketjo/k-room_client:latest
    restart: always
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'



