# When internet connection will be stable should use direct images to hub
# version: '3'

# services:
#   db:
#     container_name: k-room-db
#     restart: always
#     images: ketjo4/k-room-db
#     ports:
#       - 27017:27017
#     volumes:
#       - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#   server:
#     container_name: 'k-room-server'
#     restart: always
#     image: ketjo4/k-room-server
#     ports:
#       - '${SERVER_PORT}:${SERVER_PORT}'
#     links:
#       - 'db'
#   client:
#     container_name: 'k-room-client'
#     restart: always
#     image: ketjo4/k-room-client
#     ports:
#       - '${CLIENT_PORT}:${CLIENT_PORT}'

