version: '3'

services:
  db:
    container_name: k-room-db
    restart: always
    build: ./db/
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  # client:
  #   container_name: 'k-room-client'
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: ./client/Dockerfile
  #   ports:
  #     - '${CLIENT_PORT}:${CLIENT_PORT}'
  server:
    container_name: 'k-room-server'
    restart: always
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    links:
      - 'db'
