server {
    listen 80;
    listen [::]:80;

    server_name k-room.space;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # uncomment while generate ssl cert
    # location / {
    #     return 301 https://$host$request_uri
    # }

    # comment next block for generate ssl cert
    location / {
        proxy_pass http://client:3001/;
    }
}

server {
    listen 443 default_server ssl http2;
    listen [::]:443 ssl http2;

    server_name k-room.space;

    ssl_certificate /etc/nginx/ssl/live/k-room.space/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/k-room.space/privkey.pem;

    location / {
        proxy_pass http://client:3001/;
    }
}