import { MB_IN_BYTES, MINUTE_IN_MS } from 'global-shared'

export const STORAGE_ESTIMATE_REFRESH_INTERVAL_MS = 1 * MINUTE_IN_MS
export const STORAGE_WARNING_AVAILABLE_BYTES = 100 * MB_IN_BYTES
export const STORAGE_WARNING_USAGE_PERCENT = 90
