export const APP_MICROPHONE_WAVEFORM_DEFAULT_PROPS = {
  showIcon: true,
  loudThreshold: 85
}

export const APP_MICROPHONE_WAVEFORM_DISPLAY_MAX_DB = -12

export const APP_MICROPHONE_WAVEFORM_DISPLAY_MIN_DB = -55

export const APP_MICROPHONE_WAVEFORM_SMOOTHING = 0.75

export const APP_MICROPHONE_WAVEFORM_MIN_BAR_SCALE = 0.14

export const APP_MICROPHONE_WAVEFORM_BARS = [0.55, 0.82, 1.15, 0.92, 1.25, 0.76, 0.6]
