"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Status = exports.RouteNames = exports.SocketActions = exports.CommonEndPoints = exports.UserEndPoints = exports.AuthEndPoints = void 0;
var AuthEndPoints;
(function (AuthEndPoints) {
    AuthEndPoints["REGISTRATION"] = "/api/auth/registration";
    AuthEndPoints["SEND_EMAIL_CONFIRMATION_LINK"] = "/api/auth/send-email-confirmation-link";
    AuthEndPoints["SEND_EMAIL_CONFIRMATION"] = "/api/auth/send-email-confirmation";
    AuthEndPoints["LOGIN"] = "/api/auth/login";
    AuthEndPoints["LOGOUT"] = "/api/auth/logout";
    AuthEndPoints["UPDATE_TOKENS_PAIR"] = "/api/auth/update-tokens-pair";
})(AuthEndPoints = exports.AuthEndPoints || (exports.AuthEndPoints = {}));
var UserEndPoints;
(function (UserEndPoints) {
    UserEndPoints["GET_USER_DATA"] = "/api/auth/get-user-data";
    UserEndPoints["UPDATE_USER_DATA"] = "/api/auth/user-data/update";
    UserEndPoints["UPDATE_USER_SETTINGS"] = "/api/user/update-user-settings";
})(UserEndPoints = exports.UserEndPoints || (exports.UserEndPoints = {}));
var CommonEndPoints;
(function (CommonEndPoints) {
    CommonEndPoints["COMMON_IMAGES"] = "/api/common-images";
    CommonEndPoints["GET_FILES"] = "/api/image/:filename";
})(CommonEndPoints = exports.CommonEndPoints || (exports.CommonEndPoints = {}));
var SocketActions;
(function (SocketActions) {
    SocketActions["CONNECTION"] = "connection";
    SocketActions["RECONNECTION"] = "reconnect";
    SocketActions["RECONNECT_ATTEMPT"] = "reconnect_attempt";
    SocketActions["RECONNECT_FAILED"] = "reconnect_failed";
    SocketActions["INITIALIZE"] = "initialize";
    SocketActions["DISCONNECT"] = "disconnect";
    SocketActions["GET_ROOMS"] = "get-rooms";
    SocketActions["CREATE_ROOM"] = "create-room";
    SocketActions["SEND_MESSAGE"] = "send-message";
    SocketActions["MESSAGE_DELIVERED"] = "message-delivered";
    SocketActions["ROOM_CREATED"] = "room-created";
    SocketActions["SEARCH_CONTACT"] = "search-contact";
    SocketActions["GET_SEARCHED_CONTACTS"] = "get-searched-contact";
    SocketActions["STATUS_CONTACT"] = "status-contact";
    SocketActions["GET_CONTACTS"] = "get-contacts";
    SocketActions["SAVE_CONTACT"] = "save-contact";
    SocketActions["DELETE_CONTACT"] = "delete-contact";
    SocketActions["USER_TYPING"] = "user-typing";
    SocketActions["GET_USER_TYPING_STATUS"] = "get-user-typing-status";
    SocketActions["CHANGE_MESSAGE_STATUS"] = "change-message-status";
    SocketActions["UPDATE_MESSAGE_STATUS"] = "update-message-status";
    SocketActions["CHANGE_CONTACTS_DATA"] = "change-contacts-data";
    SocketActions["CALL_USER"] = "call-user";
    SocketActions["ANSWER_CALL"] = "answer-call";
    SocketActions["CALL_ACCEPTED"] = "call-accepted";
    SocketActions["CALL_ENDED"] = "call-ended";
})(SocketActions = exports.SocketActions || (exports.SocketActions = {}));
var RouteNames;
(function (RouteNames) {
    RouteNames["SIGN_IN"] = "/sign-in";
    RouteNames["SIGN_UP"] = "/sign-up";
    RouteNames["WAIT_EMAIL_CONFIRM"] = "/wait-email-confirm";
    RouteNames["EMAIL_CONFIRM"] = "/confirm-email";
    RouteNames["MAIN"] = "/app";
    RouteNames["NOT_FOUND"] = "/not-found";
})(RouteNames = exports.RouteNames || (exports.RouteNames = {}));
var Status;
(function (Status) {
    Status[Status["SUCCESS"] = 200] = "SUCCESS";
    Status[Status["BAD_REQUEST"] = 400] = "BAD_REQUEST";
    Status[Status["NOT_AUTH"] = 401] = "NOT_AUTH";
    Status[Status["TOKEN_EXPIRED"] = 403] = "TOKEN_EXPIRED";
    Status[Status["NOT_FOUND"] = 404] = "NOT_FOUND";
    Status[Status["UNREACHABLE"] = 503] = "UNREACHABLE";
    Status[Status["BAD_GATEAWAY"] = 504] = "BAD_GATEAWAY";
})(Status = exports.Status || (exports.Status = {}));
