export { useNotification } from './hooks/use-notification'
export type { NotificationType, UseNotificationType, IAppNotification } from './types'
export { getNotificationIcon } from './helpers/get-notification-icon'
export { ERROR_NOTIFICATION_DURATION_IN_SEC } from './internals/constants'
export { NOTIFICATION_I18N } from './internals/i18n'
export { DONT_SHOW_NOTIFICATION_AGAIN_BTN_I18N } from './components/DontShowNotificationAgainBtn/internals/i18n'
export type { IDontShowNotificationAgainBtnProps } from './components/DontShowNotificationAgainBtn/internals/types'
export { DontShowNotificationAgainBtn } from './components/DontShowNotificationAgainBtn/DontShowNotificationAgainBtn'
