version: '3'

services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ../../.env.production
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_ADMIN_MONGODB_URL}
      ME_CONFIG_SITE_BASEURL: /
  server:
    image: ketjo/k-room_server:latest
    restart: always
    ports:
      - 3000:3000
  client:
    image: ketjo/k-room_client:latest
    restart: always
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ../nginx/:/etc/nginx/conf.d/:ro
