import {
  CHAT_ROOM_NAME_MAX_LENGTH,
  MB_IN_BYTES,
  MEDIA_AVATAR_VALIDATION_OPTIONS,
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP
} from 'global-shared'

export const CREATE_CHAT_ROOM_AVATAR_ALLOWED_TYPES =
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP[MEDIA_AVATAR_VALIDATION_OPTIONS.supportedKindMediaType]
export const CREATE_CHAT_ROOM_AVATAR_MAX_MB = MEDIA_AVATAR_VALIDATION_OPTIONS.maxMb
export const CREATE_CHAT_ROOM_AVATAR_MAX_FILE_SIZE = CREATE_CHAT_ROOM_AVATAR_MAX_MB * MB_IN_BYTES
export const CHAT_ROOM_NAME_MAX_LENGTH_PATTERN = new RegExp(`^.{0,${CHAT_ROOM_NAME_MAX_LENGTH}}$`)
