export const EMAIL_CONFIRMATION_LINK_LIFE = 86_400

export const JWT_ACCESS_EXPIRES_INTERVAL = '15m'
export const REFRESH_TOKEN_EXPIRES_INTERVAL = '14d'
export const REGISTRATION_RESEND_INTERVAL = 60 * 1000 * 3
export const SEND_CONFIRMATION_LINK_INTERVAL = 60 * 1000 * 3
