export const EMAIL_CONFIRMATION_LINK_LIFE = 86_400

export const MILLISECONDS_IN_SECOND = 1000
export const MILLISECONDS_IN_MINUTE = 60 * MILLISECONDS_IN_SECOND
export const MILLISECONDS_IN_HOUR = 60 * MILLISECONDS_IN_MINUTE
export const MILLISECONDS_IN_DAY = 24 * MILLISECONDS_IN_HOUR
export const DEFAULT_COOKIE_MAX_AGE = 30 * MILLISECONDS_IN_DAY
export const TOKEN_EXPIRES_PATTERN = /^(\d+)([smhd])$/
export const TOKEN_EXPIRES_UNIT_TO_MS = {
  s: MILLISECONDS_IN_SECOND,
  m: MILLISECONDS_IN_MINUTE,
  h: MILLISECONDS_IN_HOUR,
  d: MILLISECONDS_IN_DAY
} as const

export const JWT_ACCESS_EXPIRES_INTERVAL = '15m'
export const REFRESH_TOKEN_EXPIRES_INTERVAL = '14d'
export const REGISTRATION_RESEND_INTERVAL = 3 * MILLISECONDS_IN_MINUTE
export const SEND_CONFIRMATION_LINK_INTERVAL = 3 * MILLISECONDS_IN_MINUTE
