import {
  CHAT_ROOM_GROUP_MEMBER_LIMIT,
  MB_IN_BYTES,
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP,
  MEDIA_VALIDATION_OPTIONS_MAP
} from 'global-shared'

const CREATE_CHAT_ROOM_AVATAR_VALIDATION = MEDIA_VALIDATION_OPTIONS_MAP.avatar

export const ROOM_MESSAGES_PAGE_LIMIT = 30
export const MESSAGE_READ_VISIBILITY_RATIO = 0.5
export const MESSAGE_VIRTUAL_ESTIMATED_HEIGHT = 96
export const MESSAGE_VIRTUAL_GAP = 4
export const MESSAGE_VIRTUAL_OVERSCAN = 8
export const CREATE_CHAT_ROOM_CONTACT_PICKER_LIMIT = CHAT_ROOM_GROUP_MEMBER_LIMIT - 1
export const CREATE_CHAT_ROOM_AVATAR_ALLOWED_TYPES =
  MEDIA_KIND_ALLOWED_UPLOAD_TYPES_MAP[CREATE_CHAT_ROOM_AVATAR_VALIDATION.supportedKindMediaType]
export const CREATE_CHAT_ROOM_AVATAR_MAX_MB = CREATE_CHAT_ROOM_AVATAR_VALIDATION.maxMb
export const CREATE_CHAT_ROOM_AVATAR_MAX_FILE_SIZE = CREATE_CHAT_ROOM_AVATAR_MAX_MB * MB_IN_BYTES
