import { PROTECTED_ACTION_REASON, SECURITY_ACTION } from 'global-shared'

import { SEND_CONFIRMATION_LINK_INTERVAL_MS } from '../auth/auth.constants'

export const SECURITY_REDIS_KEY_PREFIX = 'security'
export const TURNSTILE_VERIFY_URL = 'https://challenges.cloudflare.com/turnstile/v0/siteverify'
export const TURNSTILE_VERIFY_TIMEOUT_MS = 5000
export const LOGIN_FAILURE_WINDOW_MS = 15 * 60 * 1000
export const REGISTRATION_WINDOW_MS = 60 * 60 * 1000
export const EMAIL_ACTION_WINDOW_MS = 60 * 60 * 1000
export const PASSWORD_RECOVERY_CODE_WINDOW_MS = 30 * 60 * 1000
export const SEND_CONFIRMATION_LINK_COOLDOWN_MS = SEND_CONFIRMATION_LINK_INTERVAL_MS
export const LOGIN_CAPTCHA_ACCOUNT_THRESHOLD = 5
export const LOGIN_BLOCK_ACCOUNT_THRESHOLD = 10
export const LOGIN_CAPTCHA_IP_THRESHOLD = 20
export const LOGIN_BLOCK_IP_THRESHOLD = 30
export const REGISTRATION_CAPTCHA_IP_THRESHOLD = 3
export const REGISTRATION_BLOCK_IP_THRESHOLD = 5
export const SEND_CONFIRMATION_LINK_CAPTCHA_EMAIL_THRESHOLD = 3
export const SEND_CONFIRMATION_LINK_BLOCK_EMAIL_THRESHOLD = 6
export const SEND_CONFIRMATION_LINK_CAPTCHA_IP_THRESHOLD = 10
export const SEND_CONFIRMATION_LINK_BLOCK_IP_THRESHOLD = 20
export const SEND_PASSWORD_RECOVERY_CAPTCHA_EMAIL_THRESHOLD = 3
export const SEND_PASSWORD_RECOVERY_BLOCK_EMAIL_THRESHOLD = 6
export const SEND_PASSWORD_RECOVERY_CAPTCHA_IP_THRESHOLD = 10
export const SEND_PASSWORD_RECOVERY_BLOCK_IP_THRESHOLD = 20
export const SEND_CHANGE_EMAIL_CAPTCHA_EMAIL_THRESHOLD = 3
export const SEND_CHANGE_EMAIL_BLOCK_EMAIL_THRESHOLD = 6
export const SEND_CHANGE_EMAIL_CAPTCHA_IP_THRESHOLD = 10
export const SEND_CHANGE_EMAIL_BLOCK_IP_THRESHOLD = 20
export const VALIDATE_PASSWORD_RECOVERY_CAPTCHA_EMAIL_THRESHOLD = 5
export const VALIDATE_PASSWORD_RECOVERY_BLOCK_EMAIL_THRESHOLD = 8
export const VALIDATE_PASSWORD_RECOVERY_CAPTCHA_IP_THRESHOLD = 10
export const VALIDATE_PASSWORD_RECOVERY_BLOCK_IP_THRESHOLD = 15
export const VALIDATE_CHANGE_EMAIL_CAPTCHA_EMAIL_THRESHOLD = 5
export const VALIDATE_CHANGE_EMAIL_BLOCK_EMAIL_THRESHOLD = 8
export const VALIDATE_CHANGE_EMAIL_CAPTCHA_IP_THRESHOLD = 10
export const VALIDATE_CHANGE_EMAIL_BLOCK_IP_THRESHOLD = 15

export const SECURITY_BLOCK_REASON = PROTECTED_ACTION_REASON.temporarilyBlocked
export const SECURITY_CAPTCHA_REASON = PROTECTED_ACTION_REASON.captchaRequired
export const SECURITY_RATE_LIMIT_REASON = PROTECTED_ACTION_REASON.rateLimited

export const PROTECTED_SECURITY_ACTION = SECURITY_ACTION
