import { HOUR_IN_MS, MINUTE_IN_MS, SECOND_IN_MS, SECURITY_ACTION, type SecurityAction } from 'global-shared'

import { SEND_CONFIRMATION_LINK_INTERVAL_MS } from '../auth/auth.constants'

import type { SecurityEmailIpActionLimits } from './types'

export const SECURITY_REDIS_KEY_PREFIX = 'security'
export const TURNSTILE_VERIFY_URL = 'https://challenges.cloudflare.com/turnstile/v0/siteverify'
export const TURNSTILE_VERIFY_TIMEOUT_MS = 5 * SECOND_IN_MS
export const LOGIN_FAILURE_WINDOW_MS = 15 * MINUTE_IN_MS
export const REGISTRATION_WINDOW_MS = 1 * HOUR_IN_MS
export const EMAIL_ACTION_WINDOW_MS = 1 * HOUR_IN_MS
export const PASSWORD_RECOVERY_CODE_WINDOW_MS = 30 * MINUTE_IN_MS
export const SEND_CONFIRMATION_LINK_COOLDOWN_MS = SEND_CONFIRMATION_LINK_INTERVAL_MS
export const LOGIN_CAPTCHA_ACCOUNT_THRESHOLD = 5
export const LOGIN_BLOCK_ACCOUNT_THRESHOLD = 10
export const LOGIN_CAPTCHA_IP_THRESHOLD = 20
export const LOGIN_BLOCK_IP_THRESHOLD = 30
export const REGISTRATION_CAPTCHA_IP_THRESHOLD = 3
export const REGISTRATION_BLOCK_IP_THRESHOLD = 5
export const SEND_CONFIRMATION_LINK_CAPTCHA_EMAIL_THRESHOLD = 3
export const SEND_CONFIRMATION_LINK_BLOCK_EMAIL_THRESHOLD = 6
export const SEND_CONFIRMATION_LINK_CAPTCHA_IP_THRESHOLD = 10
export const SEND_CONFIRMATION_LINK_BLOCK_IP_THRESHOLD = 20
export const SEND_PASSWORD_RECOVERY_CAPTCHA_EMAIL_THRESHOLD = 3
export const SEND_PASSWORD_RECOVERY_BLOCK_EMAIL_THRESHOLD = 6
export const SEND_PASSWORD_RECOVERY_CAPTCHA_IP_THRESHOLD = 10
export const SEND_PASSWORD_RECOVERY_BLOCK_IP_THRESHOLD = 20
export const SEND_CHANGE_EMAIL_CAPTCHA_EMAIL_THRESHOLD = 3
export const SEND_CHANGE_EMAIL_BLOCK_EMAIL_THRESHOLD = 6
export const SEND_CHANGE_EMAIL_CAPTCHA_IP_THRESHOLD = 10
export const SEND_CHANGE_EMAIL_BLOCK_IP_THRESHOLD = 20
export const VALIDATE_PASSWORD_RECOVERY_CAPTCHA_EMAIL_THRESHOLD = 5
export const VALIDATE_PASSWORD_RECOVERY_BLOCK_EMAIL_THRESHOLD = 8
export const VALIDATE_PASSWORD_RECOVERY_CAPTCHA_IP_THRESHOLD = 10
export const VALIDATE_PASSWORD_RECOVERY_BLOCK_IP_THRESHOLD = 15
export const VALIDATE_CHANGE_EMAIL_CAPTCHA_EMAIL_THRESHOLD = 5
export const VALIDATE_CHANGE_EMAIL_BLOCK_EMAIL_THRESHOLD = 8
export const VALIDATE_CHANGE_EMAIL_CAPTCHA_IP_THRESHOLD = 10
export const VALIDATE_CHANGE_EMAIL_BLOCK_IP_THRESHOLD = 15

export const SECURITY_EMAIL_IP_ACTION_LIMITS = {
  [SECURITY_ACTION.sendConfirmationLink]: {
    captchaEmailThreshold: SEND_CONFIRMATION_LINK_CAPTCHA_EMAIL_THRESHOLD,
    blockEmailThreshold: SEND_CONFIRMATION_LINK_BLOCK_EMAIL_THRESHOLD,
    captchaIpThreshold: SEND_CONFIRMATION_LINK_CAPTCHA_IP_THRESHOLD,
    blockIpThreshold: SEND_CONFIRMATION_LINK_BLOCK_IP_THRESHOLD
  },
  [SECURITY_ACTION.sendPasswordRecoveryCode]: {
    captchaEmailThreshold: SEND_PASSWORD_RECOVERY_CAPTCHA_EMAIL_THRESHOLD,
    blockEmailThreshold: SEND_PASSWORD_RECOVERY_BLOCK_EMAIL_THRESHOLD,
    captchaIpThreshold: SEND_PASSWORD_RECOVERY_CAPTCHA_IP_THRESHOLD,
    blockIpThreshold: SEND_PASSWORD_RECOVERY_BLOCK_IP_THRESHOLD
  },
  [SECURITY_ACTION.sendChangeEmailCode]: {
    captchaEmailThreshold: SEND_CHANGE_EMAIL_CAPTCHA_EMAIL_THRESHOLD,
    blockEmailThreshold: SEND_CHANGE_EMAIL_BLOCK_EMAIL_THRESHOLD,
    captchaIpThreshold: SEND_CHANGE_EMAIL_CAPTCHA_IP_THRESHOLD,
    blockIpThreshold: SEND_CHANGE_EMAIL_BLOCK_IP_THRESHOLD
  },
  [SECURITY_ACTION.validateChangeEmailCode]: {
    captchaEmailThreshold: VALIDATE_CHANGE_EMAIL_CAPTCHA_EMAIL_THRESHOLD,
    blockEmailThreshold: VALIDATE_CHANGE_EMAIL_BLOCK_EMAIL_THRESHOLD,
    captchaIpThreshold: VALIDATE_CHANGE_EMAIL_CAPTCHA_IP_THRESHOLD,
    blockIpThreshold: VALIDATE_CHANGE_EMAIL_BLOCK_IP_THRESHOLD
  },
  [SECURITY_ACTION.validatePasswordRecoveryCode]: {
    captchaEmailThreshold: VALIDATE_PASSWORD_RECOVERY_CAPTCHA_EMAIL_THRESHOLD,
    blockEmailThreshold: VALIDATE_PASSWORD_RECOVERY_BLOCK_EMAIL_THRESHOLD,
    captchaIpThreshold: VALIDATE_PASSWORD_RECOVERY_CAPTCHA_IP_THRESHOLD,
    blockIpThreshold: VALIDATE_PASSWORD_RECOVERY_BLOCK_IP_THRESHOLD
  }
} satisfies Partial<Record<SecurityAction, SecurityEmailIpActionLimits>>
