export const PRESENCE_REDIS_KEY_PREFIX = 'presence'
export const PRESENCE_ONLINE_USERS_KEY = `${PRESENCE_REDIS_KEY_PREFIX}:online-users`
export const PRESENCE_SOCKET_TTL_MS = 60_000
export const PRESENCE_REFRESH_INTERVAL_MS = 20_000
export const PRESENCE_SWEEP_INTERVAL_MS = 30_000
export const PRESENCE_OFFLINE_LOCK_TTL_MS = 30_000
export const PRESENCE_USER_SET_TTL_MS = PRESENCE_SOCKET_TTL_MS * 2
export const USER_SOCKET_ROOM_PREFIX = 'user'
