# renew_before_expiry = 30 days
version = 2.3.0
archive_dir = /etc/letsencrypt/archive/k-room.space
cert = /etc/letsencrypt/live/k-room.space/cert.pem
privkey = /etc/letsencrypt/live/k-room.space/privkey.pem
chain = /etc/letsencrypt/live/k-room.space/chain.pem
fullchain = /etc/letsencrypt/live/k-room.space/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d7f9603e6ee41d2ea24f827ba1a891e6
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
k-room.space = /var/www/certbot
