import { createSendPasswordRecoveryCodeSchema, createValidatePasswordRecoveryCodeSchema } from 'global-shared'

export const SEND_PASSWORD_RECOVERY_CODE_VALIDATION = createSendPasswordRecoveryCodeSchema
export const VALIDATE_PASSWORD_RECOVERY_CODE_VALIDATION = createValidatePasswordRecoveryCodeSchema
