import { IFrontendContact } from 'common-types'

export const SEARCHED_CONTACTS_MOCK: IFrontendContact[] = [
  { id: 'user-1', username: 'User 1', interactionType: 'default' },
  { id: 'user-2', username: 'User 2', interactionType: 'invited' },
  { id: 'user-3', username: 'User 3', interactionType: 'invite-accepted' },
  { id: 'user-4', username: 'User 4', interactionType: 'invite-hidden' },
  { id: 'user-5', username: 'User 5', interactionType: 'invite-received' },
  { id: 'user-6', username: 'User 6', interactionType: 'default' },
  { id: 'user-7', username: 'User 7', interactionType: 'invited' },
  { id: 'user-8', username: 'User 8', interactionType: 'invite-accepted' },
  { id: 'user-9', username: 'User 9', interactionType: 'invite-hidden' },
  { id: 'user-10', username: 'User 10', interactionType: 'invite-received' },
  { id: 'user-11', username: 'User 11', interactionType: 'default' },
  { id: 'user-12', username: 'User 12', interactionType: 'invited' },
  { id: 'user-13', username: 'User 13', interactionType: 'invite-accepted' },
  { id: 'user-14', username: 'User 14', interactionType: 'invite-hidden' },
  { id: 'user-15', username: 'User 15', interactionType: 'invite-received' },
  { id: 'user-16', username: 'User 16', interactionType: 'default' },
  { id: 'user-17', username: 'User 17', interactionType: 'invited' },
  { id: 'user-18', username: 'User 18', interactionType: 'invite-accepted' },
  { id: 'user-19', username: 'User 19', interactionType: 'invite-hidden' },
  { id: 'user-20', username: 'User 20', interactionType: 'invite-received' },
  { id: 'user-21', username: 'User 21', interactionType: 'default' },
  { id: 'user-22', username: 'User 22', interactionType: 'invited' },
  { id: 'user-23', username: 'User 23', interactionType: 'invite-accepted' },
  { id: 'user-24', username: 'User 24', interactionType: 'invite-hidden' },
  { id: 'user-25', username: 'User 25', interactionType: 'invite-received' },
  { id: 'user-26', username: 'User 26', interactionType: 'default' },
  { id: 'user-27', username: 'User 27', interactionType: 'invited' },
  { id: 'user-28', username: 'User 28', interactionType: 'invite-accepted' },
  { id: 'user-29', username: 'User 29', interactionType: 'invite-hidden' },
  { id: 'user-30', username: 'User 30', interactionType: 'invite-received' },
  { id: 'user-31', username: 'User 31', interactionType: 'default' },
  { id: 'user-32', username: 'User 32', interactionType: 'invited' },
  { id: 'user-33', username: 'User 33', interactionType: 'invite-accepted' },
  { id: 'user-34', username: 'User 34', interactionType: 'invite-hidden' },
  { id: 'user-35', username: 'User 35', interactionType: 'invite-received' },
  { id: 'user-36', username: 'User 36', interactionType: 'default' },
  { id: 'user-37', username: 'User 37', interactionType: 'invited' },
  { id: 'user-38', username: 'User 38', interactionType: 'invite-accepted' },
  { id: 'user-39', username: 'User 39', interactionType: 'invite-hidden' },
  { id: 'user-40', username: 'User 40', interactionType: 'invite-received' }
]
