export { UIAvatar } from './UIAvatar/UIAvatar'
export { UIAvatarLoader } from './UIAvatarLoader/UIAvatarLoader'
export { UIButton } from './UIButton/UIButton'
export { UIImageLoader } from './UIImageLoader/UIImageLoader'
export { UIIcon } from './UIIcon/UIIcon'
export { UIInput } from './UIInput/UIInput'
export { UISwitch } from './UISwitch/UISwitch'
