import { IFrontendContact } from 'common'

export const DROPDOWN_CLOSE_DURATION = 260

export const SEARCHED_CONTACTS_MOCK: IFrontendContact[] = [
  { id: 'user-1', username: 'User 1', online: false, lastSeen: 0, interactionType: 'default' },
  { id: 'user-2', username: 'User 2', online: false, lastSeen: 0, interactionType: 'invited' },
  { id: 'user-3', username: 'User 3', online: false, lastSeen: 0, interactionType: 'invite-accepted' },
  { id: 'user-4', username: 'User 4', online: false, lastSeen: 0, interactionType: 'invite-hidden' },
  { id: 'user-5', username: 'User 5', online: false, lastSeen: 0, interactionType: 'invite-received' },
  { id: 'user-6', username: 'User 6', online: false, lastSeen: 0, interactionType: 'default' },
  { id: 'user-7', username: 'User 7', online: false, lastSeen: 0, interactionType: 'invited' },
  { id: 'user-8', username: 'User 8', online: false, lastSeen: 0, interactionType: 'invite-accepted' },
  { id: 'user-9', username: 'User 9', online: false, lastSeen: 0, interactionType: 'invite-hidden' },
  { id: 'user-10', username: 'User 10', online: false, lastSeen: 0, interactionType: 'invite-received' },
  { id: 'user-11', username: 'User 11', online: false, lastSeen: 0, interactionType: 'default' },
  { id: 'user-12', username: 'User 12', online: false, lastSeen: 0, interactionType: 'invited' },
  { id: 'user-13', username: 'User 13', online: false, lastSeen: 0, interactionType: 'invite-accepted' },
  { id: 'user-14', username: 'User 14', online: false, lastSeen: 0, interactionType: 'invite-hidden' },
  { id: 'user-15', username: 'User 15', online: false, lastSeen: 0, interactionType: 'invite-received' },
  { id: 'user-16', username: 'User 16', online: false, lastSeen: 0, interactionType: 'default' },
  { id: 'user-17', username: 'User 17', online: false, lastSeen: 0, interactionType: 'invited' },
  { id: 'user-18', username: 'User 18', online: false, lastSeen: 0, interactionType: 'invite-accepted' },
  { id: 'user-19', username: 'User 19', online: false, lastSeen: 0, interactionType: 'invite-hidden' },
  { id: 'user-20', username: 'User 20', online: false, lastSeen: 0, interactionType: 'invite-received' },
  { id: 'user-21', username: 'User 21', online: false, lastSeen: 0, interactionType: 'default' },
  { id: 'user-22', username: 'User 22', online: false, lastSeen: 0, interactionType: 'invited' },
  { id: 'user-23', username: 'User 23', online: false, lastSeen: 0, interactionType: 'invite-accepted' },
  { id: 'user-24', username: 'User 24', online: false, lastSeen: 0, interactionType: 'invite-hidden' },
  { id: 'user-25', username: 'User 25', online: false, lastSeen: 0, interactionType: 'invite-received' },
  { id: 'user-26', username: 'User 26', online: false, lastSeen: 0, interactionType: 'default' },
  { id: 'user-27', username: 'User 27', online: false, lastSeen: 0, interactionType: 'invited' },
  { id: 'user-28', username: 'User 28', online: false, lastSeen: 0, interactionType: 'invite-accepted' },
  { id: 'user-29', username: 'User 29', online: false, lastSeen: 0, interactionType: 'invite-hidden' },
  { id: 'user-30', username: 'User 30', online: false, lastSeen: 0, interactionType: 'invite-received' },
  { id: 'user-31', username: 'User 31', online: false, lastSeen: 0, interactionType: 'default' },
  { id: 'user-32', username: 'User 32', online: false, lastSeen: 0, interactionType: 'invited' },
  { id: 'user-33', username: 'User 33', online: false, lastSeen: 0, interactionType: 'invite-accepted' },
  { id: 'user-34', username: 'User 34', online: false, lastSeen: 0, interactionType: 'invite-hidden' },
  { id: 'user-35', username: 'User 35', online: false, lastSeen: 0, interactionType: 'invite-received' },
  { id: 'user-36', username: 'User 36', online: false, lastSeen: 0, interactionType: 'default' },
  { id: 'user-37', username: 'User 37', online: false, lastSeen: 0, interactionType: 'invited' },
  { id: 'user-38', username: 'User 38', online: false, lastSeen: 0, interactionType: 'invite-accepted' },
  { id: 'user-39', username: 'User 39', online: false, lastSeen: 0, interactionType: 'invite-hidden' },
  { id: 'user-40', username: 'User 40', online: false, lastSeen: 0, interactionType: 'invite-received' }
]
