export type AppIconSizeType = 'xxs' | 'xs' | 'small' | 'medium' | 'large' | 'fill'

export interface IAppIconProps {
  name: AppIconNameType
  size?: AppIconSizeType
}

export type AppIconNameType =
  | 'logo'
  | 'eye'
  | 'eye-blocked'
  | 'shield'
  | 'contacts'
  | 'chat'
  | 'users'
  | 'settings'
  | 'notification'
  | 'exit'
  | 'user-stub'
  | 'loader'
  | 'call'
  | 'phone'
  | 'cross'
  | 'search'
  | 'plus'
  | 'emoji'
  | 'send'
  | 'paper-clip'
  | 'mail'
  | 'video-call'
  | 'video-call-thin'
  | 'phone-call'
  | 'info'
  | 'arrow-left'
  | 'arrow-down'
  | 'phone-cancel'
  | 'mic'
  | 'mic-muted'
  | 'video-cancel'
  | 'cross-2'
  | 'dash'
  | 'expand'
  | 'google'
  | 'facebook'
  | 'reply'
  | 'forward'
  | 'exclamation'
  | 'image-stub'
  | 'trash'
  | 'warn'
  | 'thunder'
  | 'three-dots'
  | 'three-vertical-dots'
  | 'success'
